# The main config file for your Jekyll template

# Site settings
title: Get Up, My Child               # used for the html title of every page
desc: >
  We are a group dedicated to supporting neglected, abused, and abandoned children; 
  single mothers; adoptive families; and the elderly. We do so through community-building
  based on the _intentional neighboring_ model (See: Brenda Krause Eheart, Generations of Hope).
  We welcome partnerships with faith-based organizations, as we believe that religious community 
  and meaning-making can substantially aid our mission.

url: http://getupmychild.github.io      # put your website hosting url here
baseurl: ''                 # the subpath of your site, e.g. /blog
permalink: /:year/:title/   # how should we display posts url

# Meta settings
email: ammarmplumber@gmail.com
author: Ammar Plumber
twitter_username: ammar_plumber

# Put your ga tracking code below
google_analytics: 'UA-XXXXXXXX-X'

# Pagination settings
paginate: 5                           # number of posts to show per page
paginate_path: "/articles/page:num/"  # link scheme for articles, should be letf as is

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: About Us
    url: /about/
    desc: Who we are and what we do
  - title: Articles
    url: /articles/
    desc: Posts
  - title: Projects
    url: /projects/
    desc: Ongoing work
  

# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
gems:
  - jekyll-paginate

